# Generated by Django 3.0.6 on 2020-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('ip_address', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
