# Generated by Django 3.0.6 on 2020-09-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailView',
            fields=[
                ('ip_address', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('visit', models.CharField(max_length=5)),
            ],
        ),
    ]
