# Generated by Django 3.0.6 on 2020-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_detailview'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='time_visit',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='detailview',
            name='time_visit',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
